# Generated by Django 4.2.28 on 2026-02-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('incharge', 'Grievance Incharge'), ('admin', 'Admin')], max_length=20)),
                ('department', models.CharField(choices=[('bcom', 'B.Com'), ('bcom_ca', 'B.Com (Computer Applications)'), ('bcom_pa', 'B.Com (Professional Accounting)'), ('bsc_cs', 'B.Sc Computer Science'), ('bsc_cs_da', 'B.Sc CS with Data Analytics'), ('bsc_it', 'B.Sc Information Technology'), ('bca', 'BCA (Comp. Applications)'), ('cdf', 'Costume Design & Fashion (CDF)'), ('bba', 'BBA'), ('bsc_maths', 'B.Sc Mathematics'), ('bsc_chem', 'B.Sc Chemistry'), ('bsc_phy', 'B.Sc Physics')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Hostel', 'Hostel'), ('Library', 'Library'), ('Transport', 'Transport'), ('Academic', 'Academic'), ('Canteen', 'Canteen'), ('Infrastructure', 'Infrastructure')], max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
