# Generated by Django 4.2.28 on 2026-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Library', 'Library'), ('Transport', 'Transport'), ('Academic', 'Academic'), ('Canteen', 'Canteen'), ('Infrastructure', 'Infrastructure'), ('Stationary', 'Stationary'), ('Administration', 'Administration'), ('Security', 'Security'), ('FirstAid/Medical', 'FirstAid/Medical'), ('Events/Extracurricular', 'Events/Extracurricular')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('ba_english_literature', 'B.A.English Literature'), ('bcom', 'B.Com'), ('bcom_ca', 'B.Com (Computer Applications)'), ('bcom_pa', 'B.Com (Professional Accounting)'), ('bsc_cs', 'B.Sc Computer Science'), ('bsc_cs_da', 'B.Sc CS with Data Analytics'), ('bsc_it', 'B.Sc Information Technology'), ('bca', 'BCA (Comp. Applications)'), ('cdf', 'Costume Design & Fashion (CDF)'), ('bba_ca', 'BBA CA'), ('bsc_maths', 'B.Sc Mathematics'), ('bsc_chem', 'B.Sc Chemistry'), ('bsc_phy', 'B.Sc Physics'), ('bsc_botany', 'B.Sc Botany'), ('bsc_zoology', 'B.Sc Zoology'), ('mcom', 'M.Com'), ('msc_chemistry', 'M.Sc Chemistry'), ('msc_physics', 'M.Sc Physics'), ('mcom_ca', 'M.Com CA')], max_length=100),
        ),
    ]
